[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "*"
actix-server = "*"
num-traits = "*"
num-derive = "*"

[dependencies.serde]
version = "*"
features = ["derive"]

[dependencies.awc]
version = "*"
features = ["openssl"]
